_target_: asrsclassifier.core.models.ASRSClassifier

defaults:
  - loss@_here_: focal_loss
  - metric@_here_: f1_score
  - optimizer@_here_: adam
  - scheduler@_here_: sequential
  - _self_

encoder:
  _target_: asrsclassifier.core.models.nets.load_transformer
  name: "NASA-AIML/MIKA_SafeAeroBERT"
  num_labels: ???

trainable_layers: ???
